#!/usr/bin/env bash
# This script installs Nginx and opens port 80 for listening

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
