#!/usr/bin/env bash
# This script installs and configures Nginx for redirection 
# to code 301 

redirect_link="https://www.youtube.com/watch?v=QH2-TGUlwu4"
new_config="server_name _;\n\trewrite ^/redirect_me/$ $redirect_link permanent;"
sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
ufw allow 'Nginx HTTP'
echo "Hello world" > /var/www/html/index.html
sed -i "s|server_name\ _;|$new_config|" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
