#!/usr/bin/env bash
# This script installs Nginx and configures an error 
# 404 page

sudo apt-get update
sudo apt-get install -y nginx
sudo service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}"
sudo sed -i "20i $new_string" /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
