#!/usr/bin/env bash
# Configure HAProxy load balancer server

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get install haproxy=2.8.\*

echo "ENABLED=1" sudo tee -a /etc/default/haproxy
mv /etc/haproxy/haproxy.cfg{,.original}
touch /etc/haproxy/haproxy.cfg

printf %s "global
    log 127.0.0.1 local0 notice
    maxconn 2000
    user haproxy
    group haproxy

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    retries 3
    option redispatch
    timeout connect  5000
    timeout client  30000
    timeout server  30000

frontend http-in
    timeout client  30000
    bind 0:80 ssl crt /etc/letsencrypt/live/www.mukirae.tech/fullchain.pem
    default_backend servers

backend servers
    timeout connect 3000
    timeout server  30000
    balance roundrobin
    server 262337-web-01 34.227.93.59:80 check
    server 262337-web-02 18.234.192.168:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
