#!/usr/bin/env bash
# This script configures an NGINX server on a container
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
