#!/usr/bin/env bash
# This script configures an NGINX server on a container
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
