#!/usr/bin/env bash
# This script traps a signal and displays a message depending on the signal
echo $BASHPID > /var/run/holbertonscript.pid
while true; do
    echo 'To infinity and beyond'
    sleep 2
	trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit 0;' SIGTERM
	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm /var/run/holbertonscript.pid; exit 0;' SIGQUIT
done;
