#!/usr/bin/env bash
# This script traps a signal and displays a message depending on the signal
i=0
echo $BASHPID > /var/run/holbertonscript.pid
trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit 0;' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm /var/run/holbertonscript.pid; exit 0;' SIGQUIT
while [ $i ]; do
    echo 'To infinity and beyond'
    sleep 2
done;
