#!/usr/bin/env bash
#This script prints "Best School" 10 times but replaces it with "bad luck" in the 4th iteration and "good luck" in the 8th
i=1
while ((i <= 10)); do
	if ((i == 4)); then
		echo "bad luck"
	elif ((i == 8)); then
		echo "good luck"
	else
		echo "Best School"
	fi
	((i+=1))
done
