#!/usr/bin/env bash
# This script modifies the /etc/hosts file to add IPs
cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
